bootstrap

diff --git a/bootstrap b/bootstrap
--- a/bootstrap
+++ b/bootstrap
@@ -1,13 +1,13 @@
 #! /usr/bin/env bash
 
-NAME='ms'
+username='ms'
 
 if [ "$EUID" -ne 0 ]
 then
   echo ==================================
   echo Please be root
   echo ==================================
-  exit 1
+  exit 2
 fi
 
 echo ==================================
@@ -16,22 +16,28 @@ echo ==================================
 apt update
 apt upgrade -y
 
+echo ==================================
+echo "Add user $username"
+echo ==================================
 
-echo ==================================
-echo "Add user $NAME"
-echo ==================================
+# read -p "Enter username : " username
 read -s -p "Enter password : " password
-pass=$(perl -e 'print crypt($ARGV[0], "4vLP%xYGrV!M5z")' $password)
-echo "$pass"
-
-useradd -m -p $pass $NAME|| echo "User '$NAME' exists"
+egrep "^$username" /etc/passwd >/dev/null
+if [ $? -eq 0 ]; then
+	echo "$username exists!"
+	exit 1
+else
+	pass=$(perl -e 'print crypt($ARGV[0], "password")' $password)
+	useradd -m -p "$pass" "$username"
+	[ $? -eq 0 ] && echo "User has been added to system!" || echo "Failed to add a user!"
+fi
 
 
 echo ==================================
 echo Installing sudo and adding user
 echo ==================================
 apt install sudo
-adduser $NAME sudo
+adduser $username sudo
 
 echo ==================================
 echo Installing python3 and pip
@@ -39,11 +45,11 @@ echo ==================================
 apt install python3 -y
 apt install python3-pip -y
 
-sudo -i -u $NAME bash << EOF
+sudo -i -u $username bash << EOF
 echo ==================================
-echo Installing ansible as user \'$NAME\'
+echo Installing ansible as user \'$username\'
 echo ==================================
-mkdir -p /home/$NAME
+mkdir -p /home/$username
 python3 -m pip install --user ansible
 ansible --version
 EOF
